-- Migration: Add user_recommendation_queue table for persistent recommendation pools
-- This table stores pre-computed recommendation queues for each user
-- Created: 2026-05-14

-- Create the user_recommendation_queue table
CREATE TABLE IF NOT EXISTS public.user_recommendation_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  game_id BIGINT NOT NULL REFERENCES public.games(id) ON DELETE CASCADE,
  queue_position INTEGER NOT NULL,
  score NUMERIC DEFAULT 0,
  added_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  consumed BOOLEAN DEFAULT FALSE,
  consumed_at TIMESTAMP WITH TIME ZONE,
  UNIQUE(user_id, game_id)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_user_recommendation_queue_user_id 
  ON public.user_recommendation_queue(user_id);

CREATE INDEX IF NOT EXISTS idx_user_recommendation_queue_user_consumed 
  ON public.user_recommendation_queue(user_id, consumed);

CREATE INDEX IF NOT EXISTS idx_user_recommendation_queue_position 
  ON public.user_recommendation_queue(user_id, queue_position);

-- Create index for fast lookup of next unconsumed games
CREATE INDEX IF NOT EXISTS idx_user_rec_queue_next 
  ON public.user_recommendation_queue(user_id, consumed, queue_position);

-- Add comment
COMMENT ON TABLE public.user_recommendation_queue IS 
  'Stores pre-computed recommendation queues for fast swipe feed access';

-- Create function to rebuild user recommendation queue
CREATE OR REPLACE FUNCTION public.rebuild_user_recommendation_queue(
  p_user_id BIGINT,
  p_queue_size INTEGER DEFAULT 100
)
RETURNS INTEGER AS $$
DECLARE
  v_count INTEGER;
  v_next_position INTEGER;
BEGIN
  -- Get the next position after existing unconsumed items
  SELECT COALESCE(MAX(queue_position), -1) + 1 
  INTO v_next_position
  FROM public.user_recommendation_queue
  WHERE user_id = p_user_id AND consumed = FALSE;
  
  -- Insert new recommendations
  WITH seen_games AS (
    SELECT game_id 
    FROM public.user_game_actions 
    WHERE user_id = p_user_id
  ),
  genre_weights AS (
    SELECT 
      (jsonb_array_elements(uga.genres)->>'id')::INTEGER as genre_id,
      SUM(CASE 
        WHEN uga.action_type = 'like' THEN 5
        WHEN uga.action_type = 'dislike' THEN -5
        WHEN uga.action_type = 'rate' THEN COALESCE(uga.rating, 0)
        ELSE 1
      END) as weight
    FROM public.user_game_actions uga
    WHERE uga.user_id = p_user_id
      AND jsonb_typeof(uga.genres) = 'array'
    GROUP BY (jsonb_array_elements(uga.genres)->>'id')::INTEGER
  ),
  scored_games AS (
    SELECT 
      g.id as game_id,
      COALESCE(g.rating, 0) * 5 + 
      COALESCE(g.metacritic, 0) / 5 +
      COALESCE((
        SELECT SUM(gw.weight) * 10
        FROM jsonb_array_elements(g.genres) genre_obj,
             LATERAL (SELECT (genre_obj->>'id')::INTEGER as gid) genre_id,
             genre_weights gw
        WHERE gw.genre_id = genre_id.gid
      ), 0) as score
    FROM public.games g
    WHERE g.id NOT IN (SELECT game_id FROM seen_games)
      AND g.background_image IS NOT NULL
      AND g.rating >= 3.0
    ORDER BY score DESC
    LIMIT p_queue_size
  )
  INSERT INTO public.user_recommendation_queue (user_id, game_id, queue_position, score)
  SELECT 
    p_user_id,
    sg.game_id,
    v_next_position + ROW_NUMBER() OVER () - 1,
    sg.score
  FROM scored_games sg
  ON CONFLICT (user_id, game_id) DO NOTHING;
  
  GET DIAGNOSTICS v_count = ROW_COUNT;
  
  RETURN v_count;
END;
$$ LANGUAGE plpgsql;

-- Create function to get next recommendations from queue
CREATE OR REPLACE FUNCTION public.get_user_recommendations_from_queue(
  p_user_id BIGINT,
  p_limit INTEGER DEFAULT 10
)
RETURNS TABLE (
  game_id BIGINT,
  name VARCHAR,
  background_image VARCHAR,
  rating NUMERIC,
  metacritic INTEGER,
  genres JSONB,
  released DATE,
  score NUMERIC
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    rq.game_id,
    g.name,
    g.background_image,
    g.rating,
    g.metacritic,
    g.genres,
    g.released,
    rq.score
  FROM public.user_recommendation_queue rq
  JOIN public.games g ON g.id = rq.game_id
  WHERE rq.user_id = p_user_id 
    AND rq.consumed = FALSE
  ORDER BY rq.queue_position
  LIMIT p_limit;
END;
$$ LANGUAGE plpgsql;

-- Create function to mark games as consumed
CREATE OR REPLACE FUNCTION public.mark_recommendation_consumed(
  p_user_id BIGINT,
  p_game_id BIGINT
)
RETURNS VOID AS $$
BEGIN
  UPDATE public.user_recommendation_queue
  SET consumed = TRUE, consumed_at = NOW()
  WHERE user_id = p_user_id AND game_id = p_game_id;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to auto-invalidate queue on user action
CREATE OR REPLACE FUNCTION public.invalidate_recommendation_queue_on_action()
RETURNS TRIGGER AS $$
BEGIN
  -- Mark queue as needing rebuild by setting a flag in user_recommendation_state
  INSERT INTO public.user_recommendation_state (user_id, preferences_dirty, last_rebuild, updated_at)
  VALUES (NEW.user_id, TRUE, NULL, NOW())
  ON CONFLICT (user_id) 
  DO UPDATE SET 
    preferences_dirty = TRUE,
    updated_at = NOW();
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop existing trigger if exists
DROP TRIGGER IF EXISTS trg_invalidate_queue_on_action ON public.user_game_actions;

-- Create trigger
CREATE TRIGGER trg_invalidate_queue_on_action
  AFTER INSERT OR UPDATE ON public.user_game_actions
  FOR EACH ROW
  EXECUTE FUNCTION public.invalidate_recommendation_queue_on_action();

-- Add RLS policies
ALTER TABLE public.user_recommendation_queue ENABLE ROW LEVEL SECURITY;

CREATE POLICY user_recommendation_queue_users_policy
  ON public.user_recommendation_queue
  FOR ALL
  USING (auth.uid()::BIGINT = user_id);

-- Grant permissions
GRANT ALL ON public.user_recommendation_queue TO authenticated;
GRANT USAGE ON SEQUENCE public.user_recommendation_queue_id_seq TO authenticated;

-- Initial data: create recommendation state entries for existing users
INSERT INTO public.user_recommendation_state (user_id, preferences_dirty, last_rebuild, updated_at)
SELECT 
  u.id,
  TRUE as preferences_dirty,
  NULL as last_rebuild,
  NOW() as updated_at
FROM public.users u
ON CONFLICT (user_id) DO NOTHING;
